src/Entity/Forms.php
<?php

namespace App\Entity;

use App\Repository\FormsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormsRepository::class)]
class Forms
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $Title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $expiration_date = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $user_participated = null;

    #[ORM\Column(type: Types::STRING, nullable: true)]
    private $imagePath;

    #[ORM\ManyToOne(inversedBy: 'forms')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\OneToMany(mappedBy: 'Forms', targetEntity: Questions::class, cascade: ['persist', 'remove'])]
    private Collection $questions;


    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(?\DateTimeInterface $expiration_date): static
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getUserParticipated(): ?array
    {
        return $this->user_participated;
    }

    public function setUserParticipated(?array $user_participated): static
    {
        $this->user_participated = $user_participated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(?string $imagePath): self
    {
        $this->imagePath = $imagePath;

        return $this;
    }

    /**
     * @return Collection<int, Questions>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Questions $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setForms($this);
        }

        return $this;
    }

    public function removeQuestion(Questions $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getForms() === $this) {
                $question->setForms(null);
            }
        }

        return $this;
    }
}

src/Form/FormsType.php
<?php

namespace App\Form;

use App\Entity\User;

use App\Entity\Forms;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class FormsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title', null, [
                'label' => 'Titre'
            ])
            ->add('Description', null, [
                'label' => 'Description'
            ])
            ->add('expiration_date', null, [
                'label' => 'Date d\'expiration' 
            ])
            ->add('image', FileType::class, [
                'label' => 'Image de présentation',
                'mapped' => false,
                'required' => false,
            ])
            ->add('questions', CollectionType::class, [
                'entry_type' => QuestionType::class,
                'allow_add' => true,
                'by_reference' => false,
                'label' => false,
            ])
            ->add('User', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
                'required' => false,
                'mapped' => false, //aucune selection
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Forms::class,
        ]);
    }
}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class QuestionType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('question', TextType::class, [
                'label' => 'Question'
            ])
            ->add('file', FileType::class, [
                'label' => 'Fichier audio',
                'mapped' => false,
                'required' => false,
            ])
            ->add('responseType', ChoiceType::class, [
                'label' => 'Type de réponse',
                'choices' => [
                    'Texte' => 'text',
                    'Case à cocher' => 'checkbox'
                ]
            ])
            ->add('desiredAnswer', CollectionType::class, [
                'entry_type' => TextType::class,
                'allow_add' => true,
                'label' => 'Réponses souhaitées'
            ]);
            
    }


    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Form/RegistrationFormType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

class RegistrationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('agreeTerms', CheckboxType::class, [
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You should agree to our terms.',
                    ]),
                ],
            ])
            ->add('email', EmailType::class, [
                'attr' => ['class' => 'form-control'],
                'label' => 'E-mail (optionnel)'
            ])
            ->add('plainPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/FormsController.php
<?php

namespace App\Controller;

use App\Entity\Forms;
use App\Form\FormsType;
use App\Repository\FormsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[Route('/forms')]
class FormsController extends AbstractController
{
    #[Route('/', name: 'app_forms_index', methods: ['GET'])]
    public function index(FormsRepository $formsRepository): Response
    {
        return $this->render('forms/index.html.twig', [
            'forms' => $formsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_forms_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        $form = $this->createForm(FormsType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formData = $form->getData();
            $user = $this->getUser();
            $imageFile = $form['image']->getData();

            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = preg_replace('/\s+/', '-', trim(strtolower($originalFilename)));
                $newFilename = $safeFilename . '-' . $formData->getTitle() . '-thumbnail.' . $imageFile->guessExtension();
        
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );
        
                $formData->setImagePath($newFilename);
            }
            if ($user) {
                $email = (new Email())
                    ->from('rominus.27000@gmail.com')
                    ->to($user->getEmail())
                    ->subject('Votre formulaire a été créé')
                    ->text("Le nouveau Blind Test que vous avez créé à été plublier sur le site avec succès ! N'hésitez pas à le partager à vos amis !");
    
                $mailer->send($email);
            }

            $formData->setUser($user);

            $entityManager->persist($formData);
            $entityManager->flush();

            return $this->redirectToRoute('app_forms_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forms/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_forms_show', methods: ['GET'])]
    public function show(Forms $form): Response
    {
        return $this->render('forms/show.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_forms_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Forms $form, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormsType::class, $form); // Utilisez l'instance de FormsType pour éditer un formulaire
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($form->getData());
            $entityManager->flush();

            return $this->redirectToRoute('app_forms_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forms/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/delete', name: 'app_forms_delete', methods: ['POST'])]
    public function delete(Request $request, Forms $forms, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$forms->getId(), $request->request->get('_token'))) {
            $entityManager->remove($forms);
            $entityManager->flush();
        }

        // Redirection après la suppression
        return $this->redirectToRoute('app_forms_index');
    }
}

templates/forms/_delete_form.html.twig
<form method="post" action="{{ path('app_forms_delete', {'id': form.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ form.id) }}">
    <button class="btn">Delete</button>
</form>

templates/forms/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/forms/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Forms{% endblock %}

{% block body %}
    <h1>Edit Forms</h1>

    {{ include('forms/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_forms_index') }}">back to list</a>

    {{ include('forms/_delete_form.html.twig') }}
{% endblock %}

templates/forms/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forms index{% endblock %}

{% block body %}
    <h1>Forms index</h1>

    <table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Expiration_date</th>
            <th>User_participated</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for form in forms %}
            <tr>
                <td>{{ form.id }}</td>
                <td>{{ form.Title }}</td>
                <td>{{ form.Description }}</td>
                <td>{{ form.expirationDate ? form.expirationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_forms_show', {'id': form.id}) }}">show</a>
                    <a href="{{ path('app_forms_edit', {'id': form.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
    </tbody>
</table>


    <a href="{{ path('app_forms_new') }}">Create new</a>
{% endblock %}

templates/forms/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Forms{% endblock %}

{% block body %}
    <h1>Créer un nouveau blind test</h1>

    {{ form_start(form) }}
    {{ form_row(form.Title) }}
    {{ form_row(form.Description) }}
    {{ form_row(form.expiration_date) }}
     {{ form_row(form.image) }}
     <div style="display: none;">
        {{ form_row(form.User) }}
    </div>
    <h3>Questions</h3>
    <div id="questions-container" data-prototype="{{ form_widget(form.questions.vars.prototype)|e('html_attr') }}">
        {% for question in form.questions %}
            <div class="question-item">
                {{ form_row(question) }}
            </div>
        {% endfor %}
    </div>

    <button type="button" id="add-question">Ajouter une question</button>
    <button type="submit">Sauvegarder</button>
{{ form_end(form) }}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var container = document.getElementById('questions-container');
        var addButton = document.getElementById('add-question');
        var index = container.querySelectorAll('.question-item').length;

        addButton.addEventListener('click', function() {
            var prototype = container.getAttribute('data-prototype');
            var newForm = prototype.replace(/__name__/g, index);
            container.insertAdjacentHTML('beforeend', newForm);
            index++;
        });
    });
</script>
{% endblock %}

templates/forms/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forms{% endblock %}

{% block body %}
    <h1>Forms</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ form.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ form.Title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ form.Description }}</td>
            </tr>
            <tr>
                <th>Expiration_date</th>
                <td>{{ form.expirationDate ? form.expirationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_forms_index') }}">back to list</a>

    <a href="{{ path('app_forms_edit', {'id': form.id}) }}">edit</a>

    {{ include('forms/_delete_form.html.twig') }}
{% endblock %}